// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ixMAHdx2-V5Vd6tp0d1M92zH5vTJhtQ',
    appId: '1:677319350157:web:7fbf530fa94ce138e9cfc4',
    messagingSenderId: '677319350157',
    projectId: 'artfolio1-40c71',
    authDomain: 'artfolio1-40c71.firebaseapp.com',
    storageBucket: 'artfolio1-40c71.appspot.com',
    measurementId: 'G-EZCWZCFRD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6d2WxD3tL2iBkcyMG7_Hv74r3jXXk9w',
    appId: '1:677319350157:android:277010e2f4f214d7e9cfc4',
    messagingSenderId: '677319350157',
    projectId: 'artfolio1-40c71',
    storageBucket: 'artfolio1-40c71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iyxdAu6DUHsC38EWX0HrSFoxHR81_qQ',
    appId: '1:677319350157:ios:2523f05014d03500e9cfc4',
    messagingSenderId: '677319350157',
    projectId: 'artfolio1-40c71',
    storageBucket: 'artfolio1-40c71.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iyxdAu6DUHsC38EWX0HrSFoxHR81_qQ',
    appId: '1:677319350157:ios:2523f05014d03500e9cfc4',
    messagingSenderId: '677319350157',
    projectId: 'artfolio1-40c71',
    storageBucket: 'artfolio1-40c71.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2ixMAHdx2-V5Vd6tp0d1M92zH5vTJhtQ',
    appId: '1:677319350157:web:2e3b7b2e6dae8dc1e9cfc4',
    messagingSenderId: '677319350157',
    projectId: 'artfolio1-40c71',
    authDomain: 'artfolio1-40c71.firebaseapp.com',
    storageBucket: 'artfolio1-40c71.appspot.com',
    measurementId: 'G-XMS9FN3FVF',
  );
}
